### ISSUE TITLE
Does not compile with Swift 5.7

### ISSUE THREAD

**Issue by sebsto** [apple/swift-tools-support-core#348]
Hello,

I am trying to compile TSCUtility with swift 5.7 and I receive the following error message.

```
/Users/ec2-user/project_name/.build/checkouts/swift-tools-support-core/Sources/TSCUtility/FSWatch.swift:848:15: error: cannot assign value of type 'Thread' to type 'Thread?'
                self.thread = thread
```

`self.thread` is of type `Thread?` and `thread` is of type `Thread`

I don't think this is a change in Swift 5.7 as I tested the behaviour with the following sample code

```swift
@main
public struct test {
    var a : Int?

    public init() {
       let b : Int = 1
       self.a = b
       print(a!)
    }

   public static func main() {
      let _ = test();
   }   
}
```

```
ec2-user@ip-172-31-67-99 test % swift --version 
swift-driver version: 1.62.3 Apple Swift version 5.7 (swiftlang-5.7.0.123.8 clang-1400.0.29.50)
Target: arm64-apple-macosx12.0
```

**Comment by neonichu** [comment]
I think this was fixed by #346 -- any chance your checkout is older?

**Comment by sebsto** [comment]
Thank you for the quick response.

I have this in `Package.swift` 

```swift
        .package(url: "https://github.com/apple/swift-tools-support-core.git", from: "0.2.0"),
```

and it resolved to 0.2.4 for a reason I do not explain 

```json
    {
      "identity" : "swift-tools-support-core",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/apple/swift-tools-support-core.git",
      "state" : {
        "revision" : "f9bbd6b80d67408021576adf6247e17c2e957d92",
        "version" : "0.2.4"
      }
    }
```

I forced version 0.2.7 and it now works.

Thank you
