### PR TITLE
more Sendable conformances & Sendable Context

### PR DESCRIPTION
**Pull request by weissi**
Technically API breaking:

- switches `public typealias Context = Dictionary<...>` for `public struct Context`
- requires `HashingAlgorithm` and `TracingEvent(Collection)` to be `Sendable`

### CODE REVIEW

**Comment by neonichu** [comment]
@swift-ci please test

**Comment by neonichu** [comment]
We don't promise a stable API at this point, so API breakage is acceptable. We'd need to adopt any potential clients in the toolchain, of course.

**Comment by weissi** [comment]
> We don't promise a stable API at this point, so API breakage is acceptable. We'd need to adopt any potential clients in the toolchain, of course.

Yes, I'd tag it as `0.5.0` too in which case public API breakage is almost expected for 0.x packages.

**Comment by neonichu** [comment]
@swift-ci please test

File: Sources/TSCUtility/Context.swift [hunk 1]
```diff
@@ -10,8 +10,46 @@
...
+    public init(dictionaryLiteral keyValuePairs: (ObjectIdentifier, Any)...) {
+        self.backing = Dictionary(uniqueKeysWithValues: keyValuePairs)
+    }
+
+    public init(dictionaryLiteral keyValuePairs: (ObjectIdentifier, Sendable)...) {
+        self.backing = Dictionary(uniqueKeysWithValues: keyValuePairs)
+    }
+
+    @available(*, deprecated, message: "Values should be Sendable")
+    @_disfavoredOverload
```
Comment (jakepetroules) [inline Sources/TSCUtility/Context.swift:27]: one of my favorite tricks :)

File: Sources/TSCUtility/Tracing.swift [hunk 2]
```diff
@@ -135,8 +135,24 @@ public struct TracingEvent: TracingEventProtocol, Codable {
     #endif
 }
 
-public class TracingCollection: TracingCollectionProtocol {
-    public var events: [TracingEventProtocol] = []
+public final class TracingCollection: TracingCollectionProtocol, @unchecked Sendable {
```
Comment (jakepetroules) [inline Sources/TSCUtility/Tracing.swift:138]: @unchecked because of NSLock? (if so, can add a comment?) Do we have a Lock implementation in TSC which _is_ sendable, that we could use instead?

**Review by jakepetroules — APPROVED** [review]

**Comment by neonichu** [comment]
Looks like the macOS failures are all about the changes?

File: Sources/TSCUtility/Tracing.swift (hunk 2 above)
Comment (weissi) [reply Sources/TSCUtility/Tracing.swift:138]: It's unchecked because it's manually synchronised with the lock. Even if the lock itself is sendable, the compiler can't check that you've used it correctly.

The only way to get that is to use something like `NIOLockedValueBox<[TracingEventProtocol>]` but that's not available here.

File: Sources/TSCUtility/Context.swift (hunk 1 above)
Comment (weissi) [reply Sources/TSCUtility/Context.swift:27]: @jakepetroules at some point we'll need `@_overloadFavouriteness(10)` if we have need more than one level ;)

**Comment by neonichu** [comment]
@swift-ci please test

**Comment by weissi** [comment]
@neonichu Yes, that's an old Foundation SDK which doesn't have enough Sendable annotations. Which SDK is this using?

**Comment by neonichu** [comment]
@weissi I believe the Xcode installed on Swift CI is still 13A5201i, so that would mean macOS 12.0 (21A5294d). @shahmishal to double check.

**Comment by weissi** [comment]
@neonichu thanks, yeah, that's old. I removed the Sendables that are currently problematic because that Xcode also doesn't understand `@preconcurrency` :P

**Comment by neonichu** [comment]
@swift-ci please test

**Comment by weissi** [comment]
@neonichu / @jakepetroules Could we upgrade the CI? It seems ridiculously old:

```
/Users/ec2-user/jenkins/workspace/pr-swift-tools-support-core-macos/branch-main/swift-tools-support-core/Sources/TSCUtility/Context.swift:13:79: error: unknown attribute 'unchecked'
public struct Context: /* until we can remove the support for 'Any' values */ @unchecked Sendable {
                                                                              ^
```

it doesn't know about `@unchecked`??

**Comment by MaxDesiatov** [comment]
So far I've used `UnsafeSendable` instead of `@unchecked Sendable`, as in PR #382: https://github.com/apple/swift-tools-support-core/pull/382/files#diff-c659355a0fbeab4d2e87c402f625dfcd9d014493b2c5f28a0d45ea722de362ddR13

**Comment by weissi** [comment]
> So far I've used `UnsafeSendable` instead of `@unchecked Sendable`, conditional on `#if swift(<5.6)` as in PR #382: https://github.com/apple/swift-tools-support-core/pull/382/files#diff-c659355a0fbeab4d2e87c402f625dfcd9d014493b2c5f28a0d45ea722de362ddR13

Sure, but `@unchecked Sendable` got introduced with Swift 5.7 (-> https://github.com/apple/swift-evolution/blob/main/proposals/0302-concurrent-value-and-concurrent-closures.md#sendable-and-sendable-closures) and given that SwiftPM is part of the Swift toolchain it should be targeting >= 5.8 by now and not < 5.7.

So yes, I know I could put in hacks to work around this, this really shouldn't be necessary, right?

**Comment by MaxDesiatov** [comment]
AFAIR we're keeping SwiftPM compatible with older Swift version on purpose since `libSwiftPM` clients may use those. @neonichu would be able to clarify this.

Thanks for linking to that proposal, based on that `swift(<5.6)` check should really look like `swift(<5.7)`, right?

**Comment by neonichu** [comment]
> AFAIR we're keeping SwiftPM compatible with older Swift versions on purpose, since `libSwiftPM` clients may use those. @neonichu would be able to clarify this.

Yes, we can definitely not target 5.8 only. It's also not just about `libSwiftPM` clients, but we want to enable people to contribute with just the stable version of Xcode.

There's also the practical issue that Swift CI has 13A5201i installed, so we have to stay compatible with that for the time being. If that gets upgraded to a 14.x era Xcode, we could discuss requiring 5.7

**Comment by jakepetroules** [comment]
> @neonichu / @jakepetroules Could we upgrade the CI? It seems ridiculously old:
> 
> ```
> /Users/ec2-user/jenkins/workspace/pr-swift-tools-support-core-macos/branch-main/swift-tools-support-core/Sources/TSCUtility/Context.swift:13:79: error: unknown attribute 'unchecked'
> public struct Context: /* until we can remove the support for 'Any' values */ @unchecked Sendable {
>                                                                               ^
> ```
> 
> it doesn't know about `@unchecked`??

Based on @neonichu's comments just above, can you add `#if swift(...)` as needed to get this past CI checks?

**Comment by weissi** [comment]
@swift-ci please test

**Comment by weissi** [comment]
@swift-ci please test

**Comment by weissi** [comment]
@swift-ci please test

**Comment by weissi** [comment]
@swift-ci please test

**Comment by weissi** [comment]
@swift-ci please test

**Comment by weissi** [comment]
@swift-ci please test

**Comment by weissi** [comment]
@swift-ci please test

**Comment by weissi** [comment]
@swift-ci please test

**Comment by weissi** [comment]
@swift-ci please test

**Comment by MaxDesiatov** [comment]
The biggest issue I found with supporting Swift 5.5 on macOS so far is that Xcode 13.0 can't be installed on macOS Ventura, so that means that most of the time you can test compatibility of your changes with 5.5 only on CI. Or you need access to hardware that has older macOS installed. So I'm really looking forward to bumping the minimum required version to Swift 5.6 at least.

**Comment by weissi** [comment]
@swift-ci please test

**Comment by weissi** [comment]
@swift-ci please test

**Comment by weissi** [comment]
@swift-ci please test

**Comment by weissi** [comment]
@swift-ci please test

**Comment by weissi** [comment]
@MaxDesiatov do you know what this failure is? https://ci.swift.org/job/pr-swift-tools-support-core-macos/161/console

```
+ curl -s -H 'Authorization: token ****' -X POST --data '{"state": "failure", "context": "Swift Test macOS Platform", "description": "", "target_url": "https://ci.swift.org/job/pr-swift-tools-support-core-macos/161/"}' https://api.github.com/repos/apple/swift-tools-support-core/statuses/28b332bad76a294d28b58f5ce0226e4ef6bc4bde
{
  "url": "https://api.github.com/repos/apple/swift-tools-support-core/statuses/28b332bad76a294d28b58f5ce0226e4ef6bc4bde",
  "avatar_url": "https://avatars.githubusercontent.com/u/15467072?v=4",
  "id": 21249202266,
  "node_id": "[redacted]",
  "state": "failure",
  "description": "",
  "target_url": "https://ci.swift.org/job/pr-swift-tools-support-core-macos/161/",
  "context": "Swift Test macOS Platform",
  "created_at": "2023-01-27T10:55:33Z",
  "updated_at": "2023-01-27T10:55:33Z",
  "creator": {
    "login": "****",
    "id": [redacted],
    "node_id": "[redacted]",
    "avatar_url": "https://avatars.githubusercontent.com/u/15467072?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/****",
    "html_url": "https://github.com/****",
    "followers_url": "https://api.github.com/users/****/followers",
    "following_url": "[https://api.github.com/users/****/following{/other_user}](https://api.github.com/users/****/following%7B/other_user%7D)",
    "gists_url": "[https://api.github.com/users/****/gists{/gist_id}](https://api.github.com/users/****/gists%7B/gist_id%7D)",
    "starred_url": "[https://api.github.com/users/****/starred{/owner}{/repo}](https://api.github.com/users/****/starred%7B/owner%7D%7B/repo%7D)",
    "subscriptions_url": "https://api.github.com/users/****/subscriptions",
    "organizations_url": "https://api.github.com/users/****/orgs",
    "repos_url": "https://api.github.com/users/****/repos",
    "events_url": "[https://api.github.com/users/****/events{/privacy}](https://api.github.com/users/****/events%7B/privacy%7D)",
    "received_events_url": "https://api.github.com/users/****/received_events",
    "type": "User",
    "site_admin": false
  }
}
[Pipeline] }
[Pipeline] // withCredentials
[Pipeline] echo
hudson.AbortException: script returned exit code 1
[Pipeline] sh
+ /usr/local/bin/sccache --stop-server
Stopping sccache server...
Compile requests                      0
Compile requests executed             0
Cache hits                            0
Cache misses                          0
Cache timeouts                        0
Cache read errors                     0
Forced recaches                       0
Cache write errors                    0
Compilation failures                  0
Cache errors                          0
Non-cacheable compilations            0
Non-cacheable calls                   0
Non-compilation calls                 0
Unsupported compiler calls            0
Average cache write               0.000 s
Average cache read miss           0.000 s
Average cache read hit            0.000 s
Failed distributed compilations       0
Cache location                  S3, bucket: jenkins-resource-bucket-569a545
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
Setting status of 28b332bad76a294d28b58f5ce0226e4ef6bc4bde to FAILURE with url https://ci.swift.org/job/pr-swift-tools-support-core-macos/161/ and message: 'Failed
```

**Comment by weissi** [comment]
@swift-ci please test

**Comment by MaxDesiatov** [comment]
I'm not sure if I've seen this one before, but it looks like an intermittent failure to me.

**Comment by weissi** [comment]
> I'm not sure if I've seen this one before, but it looks like an intermittent failure to me.

yeah it does but I've hit it > 3 times in a row now. I'll keep trying, thanks!

**Comment by weissi** [comment]
@swift-ci please test

**Comment by MaxDesiatov** [comment]
I'm pretty sure your PR is unrelated to the failure as I can also reproduce it in https://github.com/apple/swift-tools-support-core/pull/386

**Comment by weissi** [comment]
@neonichu I'm hitting this linker error

```
[82/84] Merging module TSCBasicTests
[83/84] Merging module TSCUtilityTests
Undefined symbols for architecture x86_64:
  "_$ss8SendableMp", referenced from:
      _$ss8Sendable_pMa in Context.swift.o
ld: symbol(s) not found for architecture x86_64
[83/84] Linking swift-tools-support-corePackageTests
error: fatalError
```

which is

```
$ pbpaste | swift demangle
Undefined symbols for architecture x86_64:
  "protocol descriptor for Swift.Sendable", referenced from:
      type metadata accessor for Swift.Sendable in Context.swift.o
ld: symbol(s) not found for architecture x86_64
[83/84] Linking swift-tools-support-corePackageTests
```

a bug in either Swift or SwiftPM not managing to link `libswift_Concurrency.dylib` on macOS :|. Not sure how to proceed without upgrading the buiders here...

**Comment by weissi** [comment]
@swift-ci please test

**Comment by weissi** [comment]
@swift-ci please test

**Comment by weissi** [comment]
@swift-ci please test

**Comment by weissi** [comment]
@swift-ci please test

**Comment by weissi** [comment]
@swift-ci please test

**Comment by weissi** [comment]
@swift-ci please test

**Comment by weissi** [comment]
@swift-ci please test

**Comment by weissi** [comment]
@swift-ci please test

**Comment by weissi** [comment]
@swift-ci please test

**Comment by weissi** [comment]
@swift-ci please test

**Comment by weissi** [comment]
@swift-ci please test

**Review by neonichu — APPROVED** [review]

**Comment by weissi** [comment]
@swift-ci please test

**Comment by weissi** [comment]
@swift-ci please test

**Comment by weissi** [comment]
@swift-ci please test
