### PR TITLE
Add workspace for CI testing

### PR DESCRIPTION
**Pull request by neonichu**
This adds a workspace that references TSC itself, as well as local checkouts of SwiftPM and SourceKit-LSP. This will allow us to test all three repositories together to validate changes to TSC in PRs.

### CODE REVIEW

**Comment by neonichu** [comment]
@swift-ci please test

**Review by abertelrud — APPROVED** [review]

**Comment by neonichu** [comment]
Updated this to also contain the various dependencies of all three projects. That'll make cross-repo testing possible for any of the repos involved if necessary. We will still only be running tests for TSC, SwiftPM and SourceKit-LSP, of course.

**Comment by neonichu** [comment]
@swift-ci please test

**Comment by neonichu** [comment]
@swift-ci please test

**Comment by neonichu** [comment]
@swift-ci please test

**Comment by neonichu** [comment]
```
12:51:34 + swift test --parallel --enable-test-discovery --multiroot-data-file Utilities/ci.xcworkspace --test-product swift-tools-support-corePackageTests
12:51:34 warning: --multiroot-data-file is an *unsupported* option which can be removed at any time; do not rely on it
12:51:34 error: noEntry
```

**Comment by neonichu** [comment]
Strange, I cannot reproduce this locally with the same workspace and cloned repos. Have to investigate a bit more.

**Comment by neonichu** [comment]
Ah, the issue is that `update-checkouts` will revert the PR changes, so we need a tweak in the CI script.

**Comment by neonichu** [comment]
@swift-ci please test

**Comment by neonichu** [comment]
@swift-ci please test

**Comment by neonichu** [comment]
Looks like we need to update the toolchain for the Linux jobs, it is still 5.2.x right now, but SourceKit-LSP requires 5.3

**Comment by neonichu** [comment]
@swift-ci please test linux

**Comment by neonichu** [comment]
Hm, the Linux job is failing with:

```
/home/buildnode/jenkins/workspace/pr-swift-tools-support-core-linux/branch-main/swift-package-manager/Sources/PackageLoading/ManifestLoader.swift:548:55: error: type 'JSONEncoder.OutputFormatting' has no member 'withoutEscapingSlashes'
14:35:34             encoder.outputFormatting = [.sortedKeys, .withoutEscapingSlashes]
14:35:34                                                      ~^~~~~~~~~~~~~~~~~~~~~~
```

**Comment by tomerd** [comment]
> I guess SwiftPM on Linux potentially doesn't build with a 5.3 toolchain?

cc @shahmishal

**Comment by neonichu** [comment]
Not sure what happened to the macOS build here: 

```
14:08:45 [520/543] Testing XcodeprojTests.XcodeProjectModelTests/testBasicProjectCreation
14:08:45 [521/543] Testing XcodeprojTests.XcodeProjectModelTests/testProductReferences
14:08:45 [522/543] Testing XcodeprojTests.XcodeProjectModelTests/testTargetDependencies
14:08:45 [523/543] Testing XcodeprojTests.XcodeProjectModelTests/testTargetCreation
15:32:05 
Build timed out (after 83 minutes). Marking the build as failed.
15:32:06 Build was aborted
```

Seems like some test just hung? Wasn't able to reproduce locally.

**Comment by neonichu** [comment]
@swift-ci please test macos

**Comment by neonichu** [comment]
The Linux failure seems quite confusing, the code that's failing to compile is wrapped in `#if` for macOS: https://github.com/apple/swift-package-manager/blob/main/Sources/PackageLoading/ManifestLoader.swift#L547

**Comment by neonichu** [comment]
Oh wait, this actually just means if macOS, use 10.15, but any version of any other OS, right? That seems also confusing to me, though, since `. withoutEscapingSlashes` was added after this change was made in SwiftPM? See https://github.com/apple/swift-corelibs-foundation/commit/0048c4aa1542770b10914bbc5d2eae733f880713

**Comment by neonichu** [comment]
Oh, I see, the change never made it to the 5.3 branch, there was a recent-ish PR for it: https://github.com/apple/swift-corelibs-foundation/pull/2889

So I guess to unblock this, we should (temporarily) only use `.withoutEscapingSlashes` on macOS.

**Comment by neonichu** [comment]
Linux build should get fixed by https://github.com/apple/swift-package-manager/pull/2993

**Comment by neonichu** [comment]
apple/swift-package-manager#2993
@swift-ci please test linux

**Comment by neonichu** [comment]
```
/usr/bin/ld.gold: error: cannot find -lPackageDescription
```

That's very confusing 🤔

**Comment by shahmishal** [comment]
One thing we should look into is writing stuff to `/tmp/`, if multiple jobs are running on the same node it might step on each other. 

```
/tmp/Resources_Localized.vhrx2v/
```

**Comment by neonichu** [comment]
Looks as if the macOS build is hanging at the same test again.

**Comment by shahmishal** [comment]
``` 
501 35981 35037   0  4:36PM ??         0:00.00 (xctest)
  501 35982 35037   0  4:36PM ??         0:03.39 /Applications/Xcode-beta.app/Contents/Developer/usr/bin/xctest -XCTest CommandsTests.BuildToolTests/testNonReachableProductsAndTargetsFunctional /Users/buildnode/jenkins/workspace/pr-swift-tools-support-core-macos/branch-main/swift-tools-support-core/.build/x86_64-apple-macosx/debug/SwiftPMPackageTests.xctest
  501 35983 35037   0  4:36PM ??         0:00.00 (xctest)
  501 35984 35037   0  4:36PM ??         0:03.25 /Applications/Xcode-beta.app/Contents/Developer/usr/bin/xctest -XCTest CommandsTests.BuildToolTests/testProductAndTarget /Users/buildnode/jenkins/workspace/pr-swift-tools-support-core-macos/branch-main/swift-tools-support-core/.build/x86_64-apple-macosx/debug/SwiftPMPackageTests.xctest
  501 36285 35037   0  4:36PM ??         0:03.24 /Applications/Xcode-beta.app/Contents/Developer/usr/bin/xctest -XCTest FunctionalTests.CFamilyTargetTestCase/testCLibraryWithSpaces /Users/buildnode/jenkins/workspace/pr-swift-tools-support-core-macos/branch-main/swift-tools-support-core/.build/x86_64-apple-macosx/debug/SwiftPMPackageTests.xctest
  501 36286 35037   0  4:36PM ??         0:03.26 /Applications/Xcode-beta.app/Contents/Developer/usr/bin/xctest -XCTest FunctionalTests.CFamilyTargetTestCase/testCUsingCAndSwiftDep /Users/buildnode/jenkins/workspace/pr-swift-tools-support-core-macos/branch-main/swift-tools-support-core/.build/x86_64-apple-macosx/debug/SwiftPMPackageTests.xctest
  501 36287 35037   0  4:36PM ??         0:03.33 /Applications/Xcode-beta.app/Contents/Developer/usr/bin/xctest -XCTest FunctionalTests.DependencyResolutionTests/testExternalSimple /Users/buildnode/jenkins/workspace/pr-swift-tools-support-core-macos/branch-main/swift-tools-support-core/.build/x86_64-apple-macosx/debug/SwiftPMPackageTests.xctest
  501 36288 35037   0  4:36PM ??         0:03.26 /Applications/Xcode-beta.app/Contents/Developer/usr/bin/xctest -XCTest FunctionalTests.CFamilyTargetTestCase/testModuleMapGenerationCases /Users/buildnode/jenkins/workspace/pr-swift-tools-support-core-macos/branch-main/swift-tools-support-core/.build/x86_64-apple-macosx/debug/SwiftPMPackageTests.xctest
  501 36289 35037   0  4:36PM ??         0:03.37 /Applications/Xcode-beta.app/Contents/Developer/usr/bin/xctest -XCTest FunctionalTests.DependencyResolutionTests/testExternalComplex /Users/buildnode/jenkins/workspace/pr-swift-tools-support-core-macos/branch-main/swift-tools-support-core/.build/x86_64-apple-macosx/debug/SwiftPMPackageTests.xctest
  501 36290 35037   0  4:36PM ??         0:00.00 (xctest)
  501 36291 35037   0  4:36PM ??         0:00.00 (xctest)
  501 36292 35037   0  4:36PM ??         0:03.30 /Applications/Xcode-beta.app/Contents/Developer/usr/bin/xctest -XCTest FunctionalTests.DependencyResolutionTests/testInternalComplex /Users/buildnode/jenkins/workspace/pr-swift-tools-support-core-macos/branch-main/swift-tools-support-core/.build/x86_64-apple-macosx/debug/SwiftPMPackageTests.xctest
  501 36293 35037   0  4:36PM ??         0:03.29 /Applications/Xcode-beta.app/Contents/Developer/usr/bin/xctest -XCTest FunctionalTests.DependencyResolutionTests/testInternalSimple /Users/buildnode/jenkins/workspace/pr-swift-tools-support-core-macos/branch-main/swift-tools-support-core/.build/x86_64-apple-macosx/debug/SwiftPMPackageTests.xctest
  501 36294 35037   0  4:36PM ??         0:00.00 (xctest)
  501 36295 35037   0  4:36PM ??         0:03.20 /Applications/Xcode-beta.app/Contents/Developer/usr/bin/xctest -XCTest XcodeprojTests.FunctionalTests/testSingleModuleLibrary /Users/buildnode/jenkins/workspace/pr-swift-tools-support-core-macos/branch-main/swift-tools-support-core/.build/x86_64-apple-macosx/debug/SwiftPMPackageTests.xctest
  501 36296 35037   0  4:36PM ??         0:03.29 /Applications/Xcode-beta.app/Contents/Developer/usr/bin/xctest -XCTest XcodeprojTests.FunctionalTests/testSwiftExecWithCDep /Users/buildnode/jenkins/workspace/pr-swift-tools-support-core-macos/branch-main/swift-tools-support-core/.build/x86_64-apple-macosx/debug/SwiftPMPackageTests.xctest
  501 36297 35037   0  4:36PM ??         0:03.25 /Applications/Xcode-beta.app/Contents/Developer/usr/bin/xctest -XCTest XcodeprojTests.FunctionalTests/testXcodeProjWithPkgConfig /Users/buildnode/jenkins/workspace/pr-swift-tools-support-core-macos/branch-main/swift-tools-support-core/.build/x86_64-apple-macosx/debug/SwiftPMPackageTests.xctest
  501 36298 35037   0  4:36PM ??         0:00.00 (xctest)
  501 36299 35037   0  4:36PM ??         0:03.33 /Applications/Xcode-beta.app/Contents/Developer/usr/bin/xctest -XCTest XcodeprojTests.FunctionalTests/testSystemModule /Users/buildnode/jenkins/workspace/pr-swift-tools-support-core-macos/branch-main/swift-tools-support-core/.build/x86_64-apple-macosx/debug/SwiftPMPackageTests.xctest
  501 36300 35037   0  4:36PM ??         0:03.30 /Applications/Xcode-beta.app/Contents/Developer/usr/bin/xctest -XCTest XcodeprojTests.FunctionalTests/testModuleNamesWithNonC99Names /Users/buildnode/jenkins/workspace/pr-swift-tools-support-core-macos/branch-main/swift-tools-support-core/.build/x86_64-apple-macosx/debug/SwiftPMPackageTests.xctest
````

**Comment by neonichu** [comment]
Haven't been able to reproduce the hang locally. I think I will change the CI script such that the new tests are opt-in somehow, so that I can keep iterating on this PR without breaking CI for other TSC PRs.

**Comment by neonichu** [comment]
@swift-ci please test

**Comment by neonichu** [comment]
Actually, we'll still need to land the workspace. I'll open an additional PR which opts into running the SwiftPM and SourceKit-LSP test suites, on that one I can iterate on the issues we are seeing.
